### PR TITLE
External CSS/JS is better and easier to edit.

### PR DESCRIPTION
**Pull request by Tamunokorite**
I removed the internal css/js because it's better to work with them from external files so that we can make changes easily. I also made some minor changes that were affecting the functionality.

### CODE REVIEW

**Comment by FaderKing** [comment]
If it's about the conflicting files, @Tamunokorite then i'll get on it right now.
Git is a very sophisticated system and stuff like this happen, so don't get worried. I'll tell you how to fix things like this on the gc
Great Job man!

**Comment by Tamunokorite** [comment]
> If it's about the conflicting files, @Tamunokorite then i'll get on it right now.
> Git is a very sophisticated system and stuff like this happen, so don't get worried. I'll tell you how to fix things like this on the gc
> Great Job man!

Okay, I'll be waiting. Thanks!

**Review by FaderKing — APPROVED** [review]
Looks good!

**Comment by FaderKing** [comment]
So it looks like @Rex-Esport made a few breaking changes while you were working...
basically y'all were editing the same files simultaneously but on *different* forks and since those changes that you and @Rex-Esport made conflicted with each other Git wouldn't allow the merge.

So it seems i'll have to assess the differences between yours and charles' then start editing, it will most likely require a new PR but we'll see how it goes..

Closing for now, Ciao!

**Pull request closed without merging**
